"""
train_model_v2.py
=============================================================================
Trains a Random Forest model to predict monthly category spending.

INPUT  : monthly_summary.csv (generated by generate_training_data.py)
OUTPUT : budget_model_v2.pkl          (the trained model)
         evaluation_results.json      (MAE, RMSE, R2 metrics)
         charts/                      (PNG charts for thesis)

HOW IT WORKS (step by step):
=============================================================================
1. Load the monthly summary (180 rows: 5 users x 36 months)
2. Create "previous month" features (what did the user spend LAST month?)
3. Split into training set (years 2023-2024) and test set (year 2025)
4. Train a Random Forest model for EACH category independently
5. Evaluate against two baselines:
   - "Last Month" baseline: predict this month = last month
   - "Average" baseline:    predict this month = user's average
6. Save everything: model, metrics, charts

Author : Aura Finance Thesis Project
Date   : April 2026
=============================================================================
"""

import os
import json
import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Try to import matplotlib; if not installed, charts will be skipped
try:
    import matplotlib
    matplotlib.use('Agg')  # Non-interactive backend (no GUI needed)
    import matplotlib.pyplot as plt
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False
    print("[WARNING] matplotlib not installed. Skipping chart generation.")
    print("  Install with: pip install matplotlib")

# =============================================================================
# CONFIGURATION
# =============================================================================
CATEGORIES = ["food", "transport", "shopping", "entertainment",
              "utilities", "health", "travel", "other"]

AI_DIR     = os.path.dirname(os.path.abspath(__file__))
CHARTS_DIR = os.path.join(AI_DIR, "charts")

# =============================================================================
# STEP 1: Load and Prepare Data
# =============================================================================
def load_data() -> pd.DataFrame:
    """
    Load monthly_summary.csv and add "previous month" features.

    WHY previous-month features?
    ----------------------------
    The key insight in financial prediction is:
        "The best predictor of what you'll spend next month is what you spent this month."

    By adding last month's spending as input features, we give the model
    something meaningful to learn from. Without these, the model only knows
    income and month number -- which is not enough to capture personal habits.

    BEFORE (what the old model had):
        income -> [MODEL] -> food, transport, ...

    AFTER (what our new model has):
        income + month + prev_food + prev_transport + ... -> [MODEL] -> food, transport, ...
    """
    path = os.path.join(AI_DIR, "monthly_summary.csv")
    df = pd.read_csv(path)

    print(f"  Loaded {len(df)} monthly records from {path}")
    print(f"  Users: {sorted(df['user_id'].unique())}")
    print(f"  Months: {sorted(df['month'].unique())}")
    print()

    # Sort by user_id, year, and month to ensure correct "previous month" alignment
    df = df.sort_values(["user_id", "year", "month"]).reset_index(drop=True)

    # Add "previous month" features for each category
    # shift(1) moves each row's value DOWN by 1, so row N gets row N-1's value
    for cat in CATEGORIES:
        df[f"prev_{cat}"] = df.groupby("user_id")[cat].shift(1)

    # Add previous month's total spending
    df["prev_total"] = df.groupby("user_id")["total_spent"].shift(1)

    # Drop month 1 for each user (no "previous month" data available)
    # This is expected: we lose the first month per user (5 rows) = 55 rows remain
    df = df.dropna().reset_index(drop=True)

    print(f"  After adding previous-month features: {len(df)} rows")
    print(f"  Feature columns: income, month, prev_food, prev_transport, ..., prev_total")
    print()

    return df


# =============================================================================
# STEP 2: Define Features and Targets
# =============================================================================
def prepare_features(df: pd.DataFrame):
    """
    Split data into:
      X (features): what the model sees as INPUT
      y (targets):  what the model tries to PREDICT

    Features we use:
      - income         : user's monthly income
      - month          : month number (1-12), captures seasonality
      - prev_food      : how much the user spent on food LAST month
      - prev_transport : how much the user spent on transport LAST month
      - ... (one per category)
      - prev_total     : total spending last month

    Target:
      - food, transport, ... (this month's actual spending per category)
    """
    feature_cols = ["income", "month"] + [f"prev_{cat}" for cat in CATEGORIES] + ["prev_total"]
    target_cols  = CATEGORIES

    X = df[feature_cols]
    y = df[target_cols]

    return X, y, feature_cols, target_cols


# =============================================================================
# STEP 3: Train/Test Split
# =============================================================================
def split_data(df: pd.DataFrame, X: pd.DataFrame, y: pd.DataFrame):
    """
    Split into training and test sets using a TIME-BASED split.

    WHY time-based instead of random?
    ---------------------------------
    In financial forecasting, you train on PAST data and predict the FUTURE.
    A random split would let the model "peek" at future months, which is
    cheating. Time-based split is more realistic and academically honest.

    Training: Years 2023-2024 (24 months per user)
    Testing:  Year 2025 (12 months per user)
    """
    train_mask = df["year"] <= 2024
    test_mask  = df["year"] == 2025

    X_train = X[train_mask]
    X_test  = X[test_mask]
    y_train = y[train_mask]
    y_test  = y[test_mask]

    print(f"  Training set: {len(X_train)} rows (years 2023-2024)")
    print(f"  Test set:     {len(X_test)} rows (year 2025)")
    print()

    return X_train, X_test, y_train, y_test, train_mask, test_mask


# =============================================================================
# STEP 4: Train the Model
# =============================================================================
def train_model(X_train, y_train, feature_cols):
    """
    Train one Random Forest model per category.

    WHY one model per category?
    ---------------------------
    Each spending category has different patterns:
      - "utilities" is very stable month-to-month
      - "travel" is very spiky (0 most months, high in summer)
      - "food" is moderately consistent

    Training separate models lets each one specialize. This is called
    "multi-target regression" and it's better than forcing one model to
    predict everything at once.

    WHY Random Forest?
    ------------------
    1. Works great with small datasets (we have ~45 training rows)
    2. Handles non-linear relationships (e.g., seasonality)
    3. Provides feature importance (great for thesis)
    4. Less prone to overfitting than neural networks on small data
    5. No need for feature normalization
    """
    models = {}
    feature_importances = {}

    for cat in CATEGORIES:
        rf = RandomForestRegressor(
            n_estimators=100,     # 100 decision trees
            max_depth=6,          # Limit depth to prevent overfitting
            min_samples_leaf=3,   # Each leaf must have at least 3 samples
            random_state=42,      # Reproducible results
        )
        rf.fit(X_train, y_train[cat])
        models[cat] = rf

        # Extract feature importance (for thesis)
        importance = dict(zip(feature_cols, rf.feature_importances_))
        feature_importances[cat] = importance

        # Print top 3 most important features per category
        sorted_imp = sorted(importance.items(), key=lambda x: x[1], reverse=True)
        top3 = ", ".join(f"{k}: {v:.2f}" for k, v in sorted_imp[:3])
        print(f"    {cat:>15}: top features = {top3}")

    return models, feature_importances


# =============================================================================
# STEP 5: Evaluate
# =============================================================================
def evaluate(models, X_test, y_test, df, test_mask):
    """
    Compare our model against two baselines.

    BASELINE 1: "Last Month"
    ========================
    Predict this month's spending = exactly what was spent last month.
    This is the simplest possible prediction and is surprisingly hard to beat.

    BASELINE 2: "User Average"
    ==========================
    Predict this month's spending = user's average spending over all months.
    This captures the general level but misses trends and seasonality.

    OUR MODEL: Random Forest
    ========================
    Uses income + month + previous spending to make informed predictions.

    METRICS:
    --------
    MAE  = Mean Absolute Error   : Average $ difference (lower is better)
    RMSE = Root Mean Squared Error: Like MAE but penalizes big errors more
    R2   = R-squared             : 1.0 = perfect, 0.0 = useless, <0 = worse than average
    """
    results = {}

    for cat in CATEGORIES:
        actual     = y_test[cat].values
        predicted  = models[cat].predict(X_test)

        # Baseline 1: last month = prev_{category}
        baseline_last = X_test[f"prev_{cat}"].values

        # Baseline 2: user average (calculate from training data)
        test_df = df[test_mask]
        user_avgs = df.groupby("user_id")[cat].mean()
        baseline_avg = test_df["user_id"].map(user_avgs).values

        results[cat] = {
            "our_model": {
                "MAE":  round(mean_absolute_error(actual, predicted), 2),
                "RMSE": round(np.sqrt(mean_squared_error(actual, predicted)), 2),
                "R2":   round(r2_score(actual, predicted), 4),
            },
            "last_month_baseline": {
                "MAE":  round(mean_absolute_error(actual, baseline_last), 2),
                "RMSE": round(np.sqrt(mean_squared_error(actual, baseline_last)), 2),
                "R2":   round(r2_score(actual, baseline_last), 4),
            },
            "average_baseline": {
                "MAE":  round(mean_absolute_error(actual, baseline_avg), 2),
                "RMSE": round(np.sqrt(mean_squared_error(actual, baseline_avg)), 2),
                "R2":   round(r2_score(actual, baseline_avg), 4),
            },
            "actual_values":    [round(v, 2) for v in actual.tolist()],
            "predicted_values": [round(v, 2) for v in predicted.tolist()],
        }

    # Calculate overall (average across all categories)
    overall = {"our_model": {}, "last_month_baseline": {}, "average_baseline": {}}
    for method in overall:
        for metric in ["MAE", "RMSE", "R2"]:
            vals = [results[cat][method][metric] for cat in CATEGORIES]
            overall[method][metric] = round(sum(vals) / len(vals), 2)

    results["_overall"] = overall

    return results


# =============================================================================
# STEP 6: Generate Charts
# =============================================================================
def generate_charts(results, models, feature_cols, X_test, y_test):
    """Generate publication-quality charts for the thesis."""
    if not HAS_MATPLOTLIB:
        print("  [SKIP] Charts skipped (matplotlib not installed)")
        return

    os.makedirs(CHARTS_DIR, exist_ok=True)

    # Set a clean style
    plt.style.use('seaborn-v0_8-whitegrid')
    plt.rcParams.update({'font.size': 11, 'figure.dpi': 150})

    # --- Chart 1: MAE Comparison Bar Chart ---
    fig, ax = plt.subplots(figsize=(12, 6))
    x = np.arange(len(CATEGORIES))
    width = 0.25

    mae_ours = [results[c]["our_model"]["MAE"] for c in CATEGORIES]
    mae_last = [results[c]["last_month_baseline"]["MAE"] for c in CATEGORIES]
    mae_avg  = [results[c]["average_baseline"]["MAE"] for c in CATEGORIES]

    bars1 = ax.bar(x - width, mae_last, width, label="Last Month Baseline", color="#94a3b8", edgecolor="white")
    bars2 = ax.bar(x,         mae_avg,  width, label="Average Baseline",    color="#f59e0b", edgecolor="white")
    bars3 = ax.bar(x + width, mae_ours, width, label="Our Random Forest",   color="#10b981", edgecolor="white")

    ax.set_xlabel("Spending Category", fontweight="bold")
    ax.set_ylabel("Mean Absolute Error ($)", fontweight="bold")
    ax.set_title("Model Performance: MAE Comparison by Category", fontweight="bold", fontsize=14)
    ax.set_xticks(x)
    ax.set_xticklabels([c.capitalize() for c in CATEGORIES], rotation=25, ha="right")
    ax.legend(loc="upper right")
    ax.grid(axis="y", alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(CHARTS_DIR, "mae_comparison.png"), bbox_inches="tight")
    plt.close()
    print("    [OK] charts/mae_comparison.png")

    # --- Chart 2: Predicted vs Actual Scatter ---
    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    axes = axes.flatten()

    for i, cat in enumerate(CATEGORIES):
        ax = axes[i]
        actual = results[cat]["actual_values"]
        predicted = results[cat]["predicted_values"]

        ax.scatter(actual, predicted, alpha=0.7, color="#10b981", edgecolors="white", s=60)

        # Perfect prediction line
        all_vals = actual + predicted
        min_val = min(all_vals) * 0.8
        max_val = max(all_vals) * 1.2
        ax.plot([min_val, max_val], [min_val, max_val], "r--", alpha=0.5, label="Perfect prediction")

        ax.set_xlabel("Actual ($)", fontsize=9)
        ax.set_ylabel("Predicted ($)", fontsize=9)
        ax.set_title(cat.capitalize(), fontweight="bold")
        ax.grid(alpha=0.3)

    fig.suptitle("Predicted vs Actual Spending by Category", fontweight="bold", fontsize=14, y=1.02)
    plt.tight_layout()
    plt.savefig(os.path.join(CHARTS_DIR, "predicted_vs_actual.png"), bbox_inches="tight")
    plt.close()
    print("    [OK] charts/predicted_vs_actual.png")

    # --- Chart 3: Feature Importance (averaged across all categories) ---
    fig, ax = plt.subplots(figsize=(10, 6))

    avg_importance = {}
    for feat in feature_cols:
        total = 0
        for cat in CATEGORIES:
            total += models[cat].feature_importances_[feature_cols.index(feat)]
        avg_importance[feat] = total / len(CATEGORIES)

    sorted_feats = sorted(avg_importance.items(), key=lambda x: x[1], reverse=True)
    feat_names = [f[0] for f in sorted_feats]
    feat_vals  = [f[1] for f in sorted_feats]

    colors = ["#10b981" if v > 0.05 else "#94a3b8" for v in feat_vals]
    ax.barh(range(len(feat_names)), feat_vals, color=colors, edgecolor="white")
    ax.set_yticks(range(len(feat_names)))
    ax.set_yticklabels([n.replace("prev_", "prev ") for n in feat_names])
    ax.invert_yaxis()
    ax.set_xlabel("Importance Score", fontweight="bold")
    ax.set_title("Feature Importance (Averaged Across All Categories)", fontweight="bold", fontsize=14)
    ax.grid(axis="x", alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(CHARTS_DIR, "feature_importance.png"), bbox_inches="tight")
    plt.close()
    print("    [OK] charts/feature_importance.png")

    # --- Chart 4: Overall Summary Table as Image ---
    fig, ax = plt.subplots(figsize=(10, 4))
    ax.axis("off")

    table_data = [["Category", "Our Model MAE", "Last Month MAE", "Average MAE", "Improvement"]]
    for cat in CATEGORIES:
        ours = results[cat]["our_model"]["MAE"]
        last = results[cat]["last_month_baseline"]["MAE"]
        improvement = ((last - ours) / last * 100) if last > 0 else 0
        table_data.append([
            cat.capitalize(),
            f"${ours:,.2f}",
            f"${last:,.2f}",
            f"${results[cat]['average_baseline']['MAE']:,.2f}",
            f"{improvement:+.1f}%",
        ])

    # Overall row
    o = results["_overall"]
    imp = ((o["last_month_baseline"]["MAE"] - o["our_model"]["MAE"]) / o["last_month_baseline"]["MAE"] * 100) if o["last_month_baseline"]["MAE"] > 0 else 0
    table_data.append([
        "OVERALL",
        f"${o['our_model']['MAE']:,.2f}",
        f"${o['last_month_baseline']['MAE']:,.2f}",
        f"${o['average_baseline']['MAE']:,.2f}",
        f"{imp:+.1f}%",
    ])

    table = ax.table(cellText=table_data, loc="center", cellLoc="center")
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1, 1.5)

    # Style header row
    for j in range(len(table_data[0])):
        table[(0, j)].set_facecolor("#1e293b")
        table[(0, j)].set_text_props(color="white", fontweight="bold")
    # Style overall row
    last_row = len(table_data) - 1
    for j in range(len(table_data[0])):
        table[(last_row, j)].set_facecolor("#ecfdf5")
        table[(last_row, j)].set_text_props(fontweight="bold")

    ax.set_title("Model Evaluation Summary", fontweight="bold", fontsize=14, pad=20)

    plt.tight_layout()
    plt.savefig(os.path.join(CHARTS_DIR, "evaluation_summary.png"), bbox_inches="tight")
    plt.close()
    print("    [OK] charts/evaluation_summary.png")


# =============================================================================
# MAIN
# =============================================================================
def main():
    print("=" * 70)
    print("  AURA FINANCE -- Model Training Pipeline (v2)")
    print("=" * 70)
    print()

    # Step 1: Load data
    print("[1/6] Loading data...")
    df = load_data()

    # Step 2: Prepare features
    print("[2/6] Preparing features...")
    X, y, feature_cols, target_cols = prepare_features(df)
    print(f"  Feature count: {len(feature_cols)}")
    print(f"  Target count:  {len(target_cols)}")
    print()

    # Step 3: Split
    print("[3/6] Splitting into train/test...")
    X_train, X_test, y_train, y_test, train_mask, test_mask = split_data(df, X, y)

    # Step 4: Train
    print("[4/6] Training Random Forest models...")
    models, feat_importances = train_model(X_train, y_train, feature_cols)
    print()

    # Step 5: Evaluate
    print("[5/6] Evaluating...")
    results = evaluate(models, X_test, y_test, df, test_mask)

    # Print comparison table
    print()
    print("  " + "-" * 66)
    print(f"  {'Category':<15} {'Our Model':>12} {'Last Month':>12} {'Average':>12} {'Improve':>10}")
    print("  " + "-" * 66)
    for cat in CATEGORIES:
        ours = results[cat]["our_model"]["MAE"]
        last = results[cat]["last_month_baseline"]["MAE"]
        avg  = results[cat]["average_baseline"]["MAE"]
        imp  = ((last - ours) / last * 100) if last > 0 else 0
        print(f"  {cat:<15} ${ours:>10,.2f} ${last:>10,.2f} ${avg:>10,.2f} {imp:>+9.1f}%")

    o = results["_overall"]
    imp = ((o["last_month_baseline"]["MAE"] - o["our_model"]["MAE"]) / o["last_month_baseline"]["MAE"] * 100) if o["last_month_baseline"]["MAE"] > 0 else 0
    print("  " + "-" * 66)
    print(f"  {'OVERALL':<15} ${o['our_model']['MAE']:>10,.2f} ${o['last_month_baseline']['MAE']:>10,.2f} ${o['average_baseline']['MAE']:>10,.2f} {imp:>+9.1f}%")
    print("  " + "-" * 66)
    print()

    # Step 6: Save
    print("[6/6] Saving model and results...")

    # Save the trained models
    model_path = os.path.join(AI_DIR, "budget_model_v2.pkl")
    joblib.dump({
        "models":        models,
        "feature_cols":  feature_cols,
        "target_cols":   target_cols,
        "categories":    CATEGORIES,
    }, model_path)
    print(f"    [OK] Model saved to: {model_path}")

    # Save evaluation results
    results_path = os.path.join(AI_DIR, "evaluation_results.json")
    # Remove numpy arrays for JSON serialization
    clean_results = {}
    for k, v in results.items():
        if isinstance(v, dict):
            clean_results[k] = {}
            for k2, v2 in v.items():
                if isinstance(v2, dict):
                    clean_results[k][k2] = {kk: float(vv) if isinstance(vv, (np.floating, float)) else vv for kk, vv in v2.items()}
                elif isinstance(v2, list):
                    clean_results[k][k2] = [float(x) for x in v2]
                else:
                    clean_results[k][k2] = v2

    with open(results_path, "w") as f:
        json.dump(clean_results, f, indent=2)
    print(f"    [OK] Results saved to: {results_path}")

    # Save feature importances
    fi_path = os.path.join(AI_DIR, "feature_importances.json")
    clean_fi = {}
    for cat, imp_dict in feat_importances.items():
        clean_fi[cat] = {k: round(float(v), 4) for k, v in imp_dict.items()}
    with open(fi_path, "w") as f:
        json.dump(clean_fi, f, indent=2)
    print(f"    [OK] Feature importances saved to: {fi_path}")

    # Generate charts
    print()
    print("  Generating charts...")
    generate_charts(results, models, feature_cols, X_test, y_test)

    print()
    print("=" * 70)
    print("  DONE! Your AI model is trained and evaluated.")
    print("  Next step: Update the backend to use budget_model_v2.pkl")
    print("=" * 70)


if __name__ == "__main__":
    main()
